### ISSUE TITLE
Обновить описание проекта

### ISSUE THREAD

**Issue by DenisIzmaylov** [aiboy/awesome-telegram-ru#5]
Сейчас:
- Список крутых телеграм чатов по программированию, DevOps, QA и многому другому

Должно быть:
- Русскоговорящие профессиональные группы в Telegram, посвященные разработке, управлению, DevOps и QA

**Comment by obenjiro** [comment]
For review
https://github.com/aiboy/awesome-telegram-ru/pull/6
